### ISSUE TITLE
npm install httpexceptions gives tsc errors

### ISSUE THREAD

**Issue by WalterLeinert** [Romakita/http-exceptions#1]
> httpexceptions@1.3.0 postinstall D:\Entwicklung\Projekte\christian-lehmeier\Technologie\griso-demo\server\node_modules\httpexceptions
> tsc

../@types/chai/index.d.ts(399,18): error TS2300: Duplicate identifier 'AssertionError'.
../@types/chai/index.d.ts(411,5): error TS2300: Duplicate identifier 'export='.
../@types/express/index.d.ts(61,34): error TS2314: Generic type 'IRouter<T>' requires 1 type argument(s).
../@types/knex/index.d.ts(23,78): error TS2304: Cannot find name 'Promise'.
../@types/knex/index.d.ts(25,16): error TS2304: Cannot find name 'Promise'.
../@types/knex/index.d.ts(298,38): error TS2304: Cannot find name 'Promise'.
...

Regards,
Walter

**Comment by Romakita** [comment]
Hello Walter,

This repo isn't maintained and the new version of httpexceptions is moved to [ts-httpexceptions](https://github.com/Romakita/ts-httpexceptions).

See you ;)
Romain

**Comment by WalterLeinert** [comment]
Hi Romain,

thanks for the info.

Regards,
Walter

PS: ts.express-decorators rocks!
